<?php

declare(strict_types=1);

namespace App\Tenancy;

use InvalidArgumentException;
use Stancl\Tenancy\Contracts\TenantWithDatabase;
use Stancl\Tenancy\DatabaseConfig;
use Stancl\Tenancy\TenantDatabaseManagers\PermissionControlledMySQLDatabaseManager;

/**
 * One MySQL database AND one MySQL user per tenant.
 *
 * Why a dedicated user: with a shared app user, isolation depends entirely on
 * the application always using the right connection. With a per-tenant user
 * that only has grants on its own schema, even a bug that builds a query
 * against another tenant's database (e.g. `tenant_b.customers`) is refused by
 * MySQL itself. Defence in depth at the storage layer.
 *
 * Why this subclass: the package's statements are not idempotent. If a
 * provisioning job dies after CREATE DATABASE but before CREATE USER, a retry
 * fails forever with "database exists". Every statement here converges on the
 * desired state instead, so the provisioning job can simply be retried.
 */
class IdempotentMySQLDatabaseManager extends PermissionControlledMySQLDatabaseManager
{
    public function createDatabase(TenantWithDatabase $tenant): bool
    {
        $database = $this->identifier($tenant->database()->getName());
        $charset = $this->identifier((string) $this->database()->getConfig('charset'));
        $collation = $this->identifier((string) $this->database()->getConfig('collation'));

        $this->database()->statement(
            "CREATE DATABASE IF NOT EXISTS `{$database}` CHARACTER SET `{$charset}` COLLATE `{$collation}`"
        );

        return $this->createUser($tenant->database());
    }

    public function createUser(DatabaseConfig $databaseConfig): bool
    {
        $database = $this->identifier($databaseConfig->getName());
        $username = $this->identifier((string) $databaseConfig->getUsername());
        $password = $this->secret((string) $databaseConfig->getPassword());

        $this->database()->statement("CREATE USER IF NOT EXISTS `{$username}`@`%` IDENTIFIED BY '{$password}'");
        // Converge the password too, in case a previous attempt created the
        // user with credentials that were never persisted on the tenant.
        $this->database()->statement("ALTER USER `{$username}`@`%` IDENTIFIED BY '{$password}'");

        $grants = implode(', ', static::$grants);

        // In GRANT, `_` and `%` in a database name are wildcards. Unescaped,
        // `tenant_abc` would also match `tenantXabc`: a pattern grant wider
        // than intended (and wider than our own `tenant\_%` grant, so MySQL
        // rightly refuses it).
        $grantTarget = addcslashes($database, '_%');

        return $this->database()->statement("GRANT {$grants} ON `{$grantTarget}`.* TO `{$username}`@`%`");
    }

    public function deleteDatabase(TenantWithDatabase $tenant): bool
    {
        $database = $this->identifier($tenant->database()->getName());

        $this->database()->statement("DROP DATABASE IF EXISTS `{$database}`");

        return $this->deleteUser($tenant->database());
    }

    public function deleteUser(DatabaseConfig $databaseConfig): bool
    {
        $username = $databaseConfig->getUsername();

        if ($username === null) {
            return true;
        }

        $username = $this->identifier($username);

        return $this->database()->statement("DROP USER IF EXISTS `{$username}`@`%`");
    }

    public function databaseExists(string $name): bool
    {
        return $this->database()->selectOne(
            'SELECT COUNT(*) AS aggregate FROM information_schema.schemata WHERE schema_name = ?',
            [$name],
        )->aggregate > 0;
    }

    /**
     * DDL can't use bound parameters, so every interpolated value is
     * whitelisted. Names are generated by us, but we don't rely on that.
     */
    private function identifier(string $value): string
    {
        if (preg_match('/^[A-Za-z0-9_\-]{1,64}$/', $value) !== 1) {
            throw new InvalidArgumentException('Unsafe MySQL identifier.');
        }

        return $value;
    }

    private function secret(string $value): string
    {
        if (preg_match('/^[A-Za-z0-9]{24,128}$/', $value) !== 1) {
            throw new InvalidArgumentException('Unsafe MySQL password.');
        }

        return $value;
    }
}
